/* ---------- shared helpers ---------- */
const $ = id => document.getElementById(id);
const esc = s => String(s ?? "").replace(/[&<>"']/g, c =>
  ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const DAY = 86400000;
const today = () => new Date().toISOString().slice(0, 10);
const dayOf = s => s ? String(s).slice(0, 10) : null;
const fmtDate = s => s ? new Date(String(s).length === 10 ? s + "T12:00:00" : s)
  .toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "";
const fmtShort = d => new Date(d + "T12:00:00").toLocaleDateString(undefined, { month: "short", day: "numeric" });
const store = {
  get(k, fallback) { try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : fallback; } catch { return fallback; } },
  set(k, v) { try { localStorage.setItem(k, JSON.stringify(v)); } catch { /* private mode: in-memory only */ } },
  del(k) { try { localStorage.removeItem(k); } catch {} },
};
const ROLES = [["pilot", "Pilot"], ["dispatch", "Dispatch"], ["ground", "Ground / ramp"]];
const ROLE_LABEL = Object.fromEntries(ROLES);
const STATUSES = [["saved", "Saved"], ["applied", "Applied"], ["interview", "Interview"],
                  ["offer", "Offer"], ["rejected", "Rejected"], ["withdrawn", "Withdrawn"]];
const STATUS_LABEL = Object.fromEntries(STATUSES);
const VERDICTS = ["strong", "possible", "weak", "ineligible", "pending"];
const SOURCE_NAMES = { jobbank: "Job Bank", linkedin: "LinkedIn", eluta: "Eluta", usajobs: "USAJOBS" };
const sourceName = s => SOURCE_NAMES[s] || "company site";
const verdictOf = j => j.evaluation ? j.evaluation.verdict : "pending";
const roleOf = j => j.role || "ground";

/* =====================================================================
   Security: validation of everything loaded, and the encrypted vault
   ===================================================================== */
const safeUrl = u => { try { const x = new URL(String(u || "")); return /^https?:$/.test(x.protocol) ? x.href : ""; } catch { return ""; } };
const pick = (v, allowed, fallback) => allowed.includes(v) ? v : fallback;
const isoDay = v => /^\d{4}-\d{2}-\d{2}$/.test(v || "") ? v : null;
const str = (v, max = 500) => String(v ?? "").slice(0, max);
const ROLE_KEYS = ROLES.map(r => r[0]), STATUS_KEYS = STATUSES.map(s => s[0]);

function sanitizeJob(j) {  // jobs.json is generated by the poller, but its text comes from scraped pages
  const ev = j.evaluation && pick(j.evaluation.verdict, VERDICTS, null) ? {
    ...j.evaluation, score: Math.max(0, Math.min(100, Number(j.evaluation.score) || 0)),
    summary: str(j.evaluation.summary, 1000),
    met: [].concat(j.evaluation.met || []).map(x => str(x, 300)),
    missing: [].concat(j.evaluation.missing || []).map(x => str(x, 300)),
    dealbreakers: [].concat(j.evaluation.dealbreakers || []).map(x => str(x, 300)),
  } : null;
  return { ...j, id: str(j.id), title: str(j.title), company: str(j.company), location: str(j.location),
    url: safeUrl(j.url), apply_url: safeUrl(j.apply_url) || safeUrl(j.url), role: pick(j.role, ROLE_KEYS, "ground"),
    evaluation: ev, also_listed: (j.also_listed || []).map(l => ({ source: str(l.source, 30), url: safeUrl(l.url) })).filter(l => l.url) };
}

function sanitizeApp(a) {  // applications come from this browser, an imported file, or the sync repo
  if (!a || !a.id) return null;
  const base = { id: str(a.id, 300), updated_at: str(a.updated_at, 40) };
  if (a.deleted) return { ...base, deleted: true };
  return { ...base, company: str(a.company), title: str(a.title), location: str(a.location),
    url: safeUrl(a.url), apply_url: safeUrl(a.apply_url), role: pick(a.role, ROLE_KEYS, "ground"),
    status: pick(a.status, STATUS_KEYS, "saved"), applied_on: isoDay(a.applied_on), follow_up: isoDay(a.follow_up),
    notes: str(a.notes, 5000),
    history: (a.history || []).filter(h => STATUS_KEYS.includes(h.status)).map(h => ({ status: h.status, at: str(h.at, 40) })) };
}

const b64 = {
  enc(buf) { const bytes = new Uint8Array(buf); let out = ""; for (let i = 0; i < bytes.length; i += 0x8000) out += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return btoa(out); },
  dec(s) { return Uint8Array.from(atob(s), c => c.charCodeAt(0)); },
};

/* Same format and KDF as jobhunter/crypto.py: PBKDF2-SHA256 -> AES-256-GCM. */
const vault = {
  key: null, salt: null, iter: 600000, plaintext: false, data: { applications: {}, sync: null }, pending: Promise.resolve(),
  async derive(password, saltB64, iterations) {
    const base = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveKey"]);
    return crypto.subtle.deriveKey({ name: "PBKDF2", hash: "SHA-256", salt: b64.dec(saltB64), iterations }, base,
                                   { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]);  // non-extractable
  },
  async decrypt(blob, key = this.key) {
    const pt = await crypto.subtle.decrypt({ name: "AES-GCM", iv: b64.dec(blob.iv) }, key, b64.dec(blob.ct));
    return JSON.parse(new TextDecoder().decode(pt));
  },
  async encrypt(obj) {
    const iv = crypto.getRandomValues(new Uint8Array(12));
    const ct = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, this.key, new TextEncoder().encode(JSON.stringify(obj)));
    return { v: 1, kdf: "PBKDF2-SHA256", iter: this.iter, salt: this.salt, iv: b64.enc(iv), ct: b64.enc(ct) };
  },
  async load() {
    if (this.plaintext) { this.data = store.get("dev-vault", this.data); }
    else {
      const blob = store.get("vault", null);
      if (blob && blob.salt === this.salt) {
        try { this.data = await this.decrypt(blob); } catch { /* saved under an older password: start fresh */ }
      }
    }
    // migrate data saved unencrypted by earlier versions of this page, then delete it
    const legacyApps = store.get("applications", null), legacySync = store.get("sync", null);
    if (legacyApps) Object.assign(this.data.applications, legacyApps);
    if (legacySync && !this.data.sync) this.data.sync = legacySync;
    store.del("applications"); store.del("sync");
    if (legacyApps || legacySync) this.save();
  },
  save() {  // serialized so an older write can't land after a newer one
    this.pending = this.pending.then(async () => {
      if (this.plaintext) store.set("dev-vault", this.data);
      else if (this.key) store.set("vault", await this.encrypt(this.data));
    }).catch(() => {});
  },
};

/* Remember-me: the derived CryptoKey (non-extractable) kept in IndexedDB for this origin. */
const keystore = {
  open() { return new Promise((res, rej) => { const r = indexedDB.open("job-hunter", 1);
    r.onupgradeneeded = () => r.result.createObjectStore("keys"); r.onsuccess = () => res(r.result); r.onerror = () => rej(r.error); }); },
  async run(mode, fn) { try { const db = await this.open(); return await new Promise(res => {
    const req = fn(db.transaction("keys", mode).objectStore("keys")); req.onsuccess = () => res(req.result ?? null); req.onerror = () => res(null); });
  } catch { return null; } },
  get() { return this.run("readonly", s => s.get("site")); },
  put(v) { return this.run("readwrite", s => s.put(v, "site")); },
  clear() { return this.run("readwrite", s => s.delete("site")); },
};

const state = { jobs: [], byId: {}, verdict: "", updated: null };

/* ---------- tabs ---------- */
function showTab(name) {
  document.querySelectorAll(".tab").forEach(t => t.setAttribute("aria-selected", t.dataset.tab === name));
  ["jobs", "apps", "trends"].forEach(n => $(`tab-${n}`).hidden = n !== name);
  store.set("tab", name);
  if (name === "trends") renderTrends();
  if (name === "apps") renderApps();
}
document.querySelectorAll(".tab").forEach(t => t.addEventListener("click", () => showTab(t.dataset.tab)));

/* =====================================================================
   Application tracker: localStorage, optionally synced to a GitHub file
   ===================================================================== */
const tracker = {
  apps: {},        // id -> application (deleted ones keep a tombstone); loaded from the vault after unlock
  list() { return Object.values(this.apps).filter(a => !a.deleted); },
  get(id) { const a = this.apps[id]; return a && !a.deleted ? a : null; },
  save(app) {
    app.updated_at = new Date().toISOString();
    this.apps[app.id] = app;
    vault.data.applications = this.apps; vault.save();
    sync.schedule();
    $("app-count").textContent = this.list().length ? `(${this.list().length})` : "";
  },
  setStatus(id, status, job) {
    let app = this.get(id);
    if (!status) { if (app) this.save({ id, deleted: true }); return; }
    if (!app) {
      app = { id, company: job.company, title: job.title, location: job.location, url: job.url,
              apply_url: job.apply_url || job.url, role: roleOf(job), notes: "", history: [] };
    }
    if (app.status !== status) app.history = [...(app.history || []), { status, at: new Date().toISOString() }];
    app.status = status;
    if (status === "applied" && !app.applied_on) app.applied_on = today();
    this.save(app);
  },
  merge(remote) {  // newest edit per id wins, so two devices can both make changes
    let changed = false;
    for (const raw of remote || []) {
      const r = sanitizeApp(raw); if (!r) continue;
      const l = this.apps[r.id];
      if (!l || (r.updated_at || "") > (l.updated_at || "")) { this.apps[r.id] = r; changed = true; }
    }
    vault.data.applications = this.apps; vault.save();
    return changed;
  },
  file() { return { applications: Object.values(this.apps), updated: new Date().toISOString() }; },
};

const sync = {
  cfg: null, sha: null, timer: null,
  status(text, cls = "") { $("sync-status").innerHTML = `<span class="${cls}">${esc(text)}</span>`; },
  valid(c) {
    return /^[\w.-]+\/[\w.-]+$/.test(c.repo) && /^[\w.\/-]+\.json$/.test(c.path) && !c.path.split("/").includes("..")
      && /^[\w.\/-]*$/.test(c.branch) && /^(github_pat_|ghp_)[\w]+$/.test(c.token);
  },
  api(query = "") {
    const c = this.cfg, path = c.path.replace(/^\/+/, "").split("/").map(encodeURIComponent).join("/");
    return `https://api.github.com/repos/${c.repo}/contents/${path}${query}`;  // the token only ever goes to api.github.com
  },
  headers() { return { Authorization: `Bearer ${this.cfg.token}`, Accept: "application/vnd.github+json" }; },
  async pull() {
    if (!this.cfg) { this.status("Saved in this browser only"); return; }
    this.status("Syncing…");
    try {
      const r = await fetch(this.api(this.cfg.branch ? `?ref=${encodeURIComponent(this.cfg.branch)}` : ""),
                            { headers: this.headers(), cache: "no-store" });
      if (r.status === 404) { this.sha = null; await this.push(); return; }
      if (!r.ok) throw new Error(`GitHub ${r.status}`);
      const body = await r.json();
      this.sha = body.sha;
      let remote = JSON.parse(new TextDecoder().decode(b64.dec(body.content.replace(/\n/g, ""))));
      let legacyPlain = false;
      if (remote.ct) {
        if (vault.plaintext) throw new Error("file is encrypted; open the published site instead");
        if (remote.salt !== vault.salt) throw new Error("file was encrypted for a different site password");
        remote = await vault.decrypt(remote);
      } else legacyPlain = true;
      tracker.merge(remote.applications);
      const remoteIds = new Set((remote.applications || []).map(a => a.id + a.updated_at));
      const localAhead = Object.values(tracker.apps).some(a => !remoteIds.has(a.id + a.updated_at));
      if (localAhead || (legacyPlain && !vault.plaintext)) await this.push(); else this.status(`Synced ${new Date().toLocaleTimeString()}`, "sync-ok");
      renderAll();
    } catch (e) { this.status(`Sync failed: ${e.message}`, "sync-err"); }
  },
  async push() {
    if (!this.cfg) return;
    // the synced file is encrypted with the site key, so it is safe even in a public repo
    const payload = vault.plaintext ? tracker.file() : await vault.encrypt(tracker.file());
    const json = JSON.stringify(payload, null, 1) + "\n";
    const content = btoa(Array.from(new TextEncoder().encode(json), b => String.fromCharCode(b)).join(""));
    const body = { message: "Update job applications", content, ...(this.sha ? { sha: this.sha } : {}),
                   ...(this.cfg.branch ? { branch: this.cfg.branch } : {}) };
    const r = await fetch(this.api(), { method: "PUT", headers: this.headers(), body: JSON.stringify(body) });
    if (r.status === 409 || r.status === 422) { await this.pull(); return; }  // edited elsewhere: merge, retry
    if (!r.ok) { this.status(`Sync failed: GitHub ${r.status}`, "sync-err"); return; }
    this.sha = (await r.json()).content.sha;
    this.status(`Synced ${new Date().toLocaleTimeString()}`, "sync-ok");
  },
  schedule() {
    if (!this.cfg) return;
    clearTimeout(this.timer);
    this.status("Unsaved changes…");
    this.timer = setTimeout(() => this.push().catch(e => this.status(`Sync failed: ${e.message}`, "sync-err")), 1500);
  },
};

/* ---------- "did you apply?" prompt after following an Apply link ---------- */
let pendingApply = null;
function openApply(id) {
  pendingApply = id;
  const app = tracker.get(id);
  if (!app) tracker.setStatus(id, "saved", state.byId[id]);
}
document.addEventListener("visibilitychange", () => {
  if (document.visibilityState !== "visible" || !pendingApply) return;
  const id = pendingApply; pendingApply = null;
  const app = tracker.get(id);
  if (!app || ["applied", "interview", "offer"].includes(app.status)) return;
  $("toast").innerHTML = `Did you apply to <b>${esc(app.title)}</b> at ${esc(app.company)}?
    <div class="actions"><button class="btn primary" id="toast-yes">Yes, mark applied</button>
    <button class="btn" id="toast-no">Not yet</button></div>`;
  $("toast").hidden = false;
  $("toast-yes").onclick = () => { tracker.setStatus(id, "applied"); $("toast").hidden = true; renderAll(); };
  $("toast-no").onclick = () => { $("toast").hidden = true; renderAll(); };
});

/* =====================================================================
   Jobs tab
   ===================================================================== */
const statusSelect = (id, current, cls = "") => `<select class="${cls}" data-track="${esc(id)}" aria-label="Application status">
  <option value="">${current ? "Untrack" : "Track…"}</option>
  ${STATUSES.map(([v, l]) => `<option value="${v}" ${current === v ? "selected" : ""}>${l}</option>`).join("")}</select>`;
const sourcesLine = j => {
  const links = (j.also_listed || []).map(l => `<a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">${esc(sourceName(l.source))}</a>`);
  return `via ${esc(sourceName(j.id.split(":")[0]))}${links.length ? ` · also on ${links.join(", ")}` : ""}`;
};
const list = (title, items) => items && items.length
  ? `<div><h4>${title}</h4><ul>${items.map(i => `<li>${esc(i)}</li>`).join("")}</ul></div>` : "";

function renderJobs() {
  const q = $("q").value.trim().toLowerCase(), company = $("company").value, role = $("role").value;
  const visible = state.jobs.filter(j => ($("closed").checked || j.active) && (!role || roleOf(j) === role)
                                         && !($("hide-tracked").checked && tracker.get(j.id)));
  const counts = Object.fromEntries(VERDICTS.map(v => [v, 0]));
  visible.forEach(j => counts[verdictOf(j)]++);
  $("stats").innerHTML = [["", "All", visible.length], ...VERDICTS.map(v => [v, v, counts[v]])]
    .map(([v, label, n]) => `<div class="stat ${state.verdict === v ? "on" : ""}" data-v="${v}"
       style="${v ? `color:var(--${v})` : ""}"><b>${n}</b>${label}</div>`).join("");

  const jobs = visible.filter(j => (!state.verdict || verdictOf(j) === state.verdict) && (!company || j.company === company)
    && (!q || `${j.title} ${j.company} ${j.location}`.toLowerCase().includes(q)));
  jobs.sort($("sort").value === "score"
    ? (a, b) => (b.evaluation?.score ?? -1) - (a.evaluation?.score ?? -1) || b.first_seen.localeCompare(a.first_seen)
    : (a, b) => b.first_seen.localeCompare(a.first_seen));

  $("list").innerHTML = jobs.length ? jobs.map(j => {
    const ev = j.evaluation, v = verdictOf(j), app = tracker.get(j.id);
    return `<article class="job ${j.active ? "" : "closed"}">
      <div class="top">
        <div class="score" style="background:var(--${v})">${ev ? ev.score : "–"}</div>
        <div class="info">
          <a class="title" href="${esc(j.url)}" target="_blank" rel="noopener noreferrer">${esc(j.title)}</a>
          <span class="badge" style="color:var(--${v})">${v}</span>
          ${app ? `<span class="badge" style="color:var(--${app.status})">${STATUS_LABEL[app.status]}</span>` : ""}
          ${j.active ? "" : `<span class="badge" style="color:var(--muted)">closed ${fmtDate(j.closed_at)}</span>`}
          <div class="meta">${esc(j.company)} · ${esc(j.location || "Location n/a")} · ${ROLE_LABEL[roleOf(j)]} ·
            found ${fmtDate(j.first_seen)} · ${sourcesLine(j)}</div>
        </div>
      </div>
      ${ev ? `<p class="summary">${esc(ev.summary)}</p>
        <details><summary>Requirement breakdown</summary><div class="cols">
          ${list("Dealbreakers", ev.dealbreakers)}${list("Missing", ev.missing)}${list("You meet", ev.met)}
        </div></details>` : ""}
      <div class="actions">
        ${j.active && j.apply_url ? `<a class="btn primary" href="${esc(j.apply_url)}" target="_blank" rel="noopener noreferrer"
            data-apply="${esc(j.id)}">Apply ↗</a>` : ""}
        ${j.url ? `<a class="btn" href="${esc(j.url)}" target="_blank" rel="noopener noreferrer">View posting</a>` : ""}
        ${statusSelect(j.id, app?.status)}
      </div>
    </article>`;
  }).join("") : `<div class="empty">No postings match these filters.</div>`;
}

/* =====================================================================
   Applications tab
   ===================================================================== */
function renderApps() {
  const apps = tracker.list();
  const counts = Object.fromEntries(STATUSES.map(([s]) => [s, 0]));
  apps.forEach(a => counts[a.status]++);
  const sent = apps.filter(a => a.applied_on).length;
  const replies = apps.filter(a => ["interview", "offer"].includes(a.status)).length;
  $("app-tiles").innerHTML = [
    ...STATUSES.slice(0, 5).map(([s, l]) => [l, counts[s], s]),
    ["Interview rate", sent ? `${Math.round(100 * replies / sent)}%` : "–", null, `${replies} of ${sent} applications`],
  ].map(([label, value, s, hint]) => `<div class="tile"><div class="label">${s ? `<span class="dot" style="background:var(--${s})"></span>` : ""}${label}</div>
     <div class="value">${value}</div>${hint ? `<div class="hint">${hint}</div>` : ""}</div>`).join("");

  const filter = $("app-filter").value;
  const shown = apps.filter(a => !filter || a.status === filter)
    .sort((a, b) => (b.applied_on || b.updated_at || "").localeCompare(a.applied_on || a.updated_at || ""));
  $("app-list").innerHTML = shown.length ? shown.map(a => {
    const job = state.byId[a.id];
    const posting = job ? (job.active ? "Posting open" : `Posting closed ${fmtDate(job.closed_at)}`) : (a.id.startsWith("manual:") ? "Added manually" : "Posting no longer tracked");
    const waited = a.applied_on && a.status === "applied" ? Math.floor((Date.now() - new Date(a.applied_on + "T12:00:00")) / DAY) : null;
    return `<article class="card app-card" data-app="${esc(a.id)}">
      <div class="app-grid">
        <div>
          <a class="title" href="${esc(a.url || "#")}" target="_blank" rel="noopener noreferrer">${esc(a.title)}</a>
          <span class="badge" style="color:var(--${a.status})">${STATUS_LABEL[a.status]}</span>
          <div class="meta">${esc(a.company)}${a.location ? ` · ${esc(a.location)}` : ""} · ${ROLE_LABEL[a.role] || ""} · ${posting}
            ${waited !== null ? ` · ${waited} day${waited === 1 ? "" : "s"} since applying` : ""}</div>
        </div>
        <div class="actions" style="margin:0">
          ${a.apply_url && a.status === "saved" && job?.active !== false ? `<a class="btn" href="${esc(a.apply_url)}" target="_blank" rel="noopener noreferrer">Apply ↗</a>` : ""}
          <button class="btn" data-remove="${esc(a.id)}" aria-label="Remove">Remove</button>
        </div>
      </div>
      <div class="app-fields">
        <label>Status ${statusSelect(a.id, a.status)}</label>
        <label>Applied on <input type="date" data-field="applied_on" value="${esc(a.applied_on || "")}"></label>
        <label>Follow up <input type="date" data-field="follow_up" value="${esc(a.follow_up || "")}"></label>
      </div>
      <textarea data-field="notes" placeholder="Notes: contact, interview date, references…">${esc(a.notes || "")}</textarea>
      ${(a.history || []).length ? `<div class="note">History: ${a.history.map(h => `${STATUS_LABEL[h.status]} ${fmtDate(h.at)}`).join(" → ")}</div>` : ""}
    </article>`;
  }).join("") : `<div class="empty">${apps.length ? "No applications with this status." :
      "No applications yet. Use <b>Track…</b> on a job card, click <b>Apply</b>, or add one manually."}</div>`;
}

/* =====================================================================
   Trends tab: everything is derived from jobs.json (first_seen / closed_at)
   ===================================================================== */
const svgNS = "http://www.w3.org/2000/svg";
const niceMax = v => { if (v <= 5) return 5; const p = 10 ** Math.floor(Math.log10(v)); const n = v / p;
  return (n <= 1 ? 1 : n <= 2 ? 2 : n <= 5 ? 5 : 10) * p; };
const ticks = max => { const step = [1, 2, 5, 10, 20, 25, 50, 100, 200, 250, 500, 1000].find(s => max / s <= 5) || max / 5;
  const out = []; for (let t = 0; t <= max + 1e-9; t += step) out.push(t); return out; };
const dateRange = (from, to) => { const out = []; for (let d = new Date(from + "T12:00:00"); d <= new Date(to + "T12:00:00"); d = new Date(+d + DAY)) out.push(d.toISOString().slice(0, 10)); return out; };
const weekStart = iso => { const d = new Date(iso + "T12:00:00"); d.setDate(d.getDate() - ((d.getDay() + 6) % 7)); return d.toISOString().slice(0, 10); };
const median = xs => { if (!xs.length) return null; const s = [...xs].sort((a, b) => a - b), m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; };
const daysBetween = (a, b) => { const d = Math.round((new Date(dayOf(b)) - new Date(dayOf(a))) / DAY);
  return Number.isFinite(d) ? Math.max(0, d) : null; };
const openDays = j => daysBetween(/^\d{4}-\d{2}-\d{2}/.test(j.posted || "") ? j.posted : j.first_seen, j.closed_at);

function tooltip(chart, html, x, y) {
  let tip = chart.querySelector(".tooltip");
  if (!tip) { tip = document.createElement("div"); tip.className = "tooltip"; chart.appendChild(tip); }
  if (!html) { tip.remove(); return; }
  tip.innerHTML = html;
  const w = chart.clientWidth, tw = tip.offsetWidth;
  tip.style.left = `${Math.min(Math.max(0, x + 12), w - tw)}px`;
  tip.style.top = `${Math.max(0, y - 10)}px`;
}
const tipRow = (color, label, value) => `<div class="row"><span class="key" style="background:${color}"></span><span>${esc(label)}</span><span>${value}</span></div>`;
const legendHtml = items => items.map(([color, label]) => `<span><span class="key" style="background:${color}"></span>${esc(label)}</span>`).join("");
const tableHtml = (head, rows) => `<div class="table-wrap"><table class="data"><thead><tr>${head.map((h, i) => `<th class="${i ? "num" : ""}">${esc(h)}</th>`).join("")}</tr></thead>
  <tbody>${rows.map(r => `<tr>${r.map((c, i) => `<td class="${i ? "num" : ""}">${esc(c)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;

function lineChart(el, dates, series) {  // series: [{key,label,color,values}]
  const W = Math.max(320, el.clientWidth || 600), H = 240, m = { t: 12, r: 104, b: 26, l: 36 };
  const max = niceMax(Math.max(1, ...series.flatMap(s => s.values)));
  const x = i => m.l + (dates.length < 2 ? (W - m.l - m.r) / 2 : i * (W - m.l - m.r) / (dates.length - 1));
  const y = v => H - m.b - v / max * (H - m.t - m.b);
  const every = Math.max(1, Math.ceil(dates.length / Math.max(2, Math.floor((W - m.l - m.r) / 70))));
  let svg = `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Open postings over time by role">`;
  ticks(max).forEach(t => svg += `<line class="gridline" x1="${m.l}" x2="${W - m.r}" y1="${y(t)}" y2="${y(t)}"/><text x="${m.l - 6}" y="${y(t) + 4}" text-anchor="end">${t.toLocaleString()}</text>`);
  dates.forEach((d, i) => { if (i % every === 0 || i === dates.length - 1) svg += `<text x="${x(i)}" y="${H - 8}" text-anchor="middle">${fmtShort(d)}</text>`; });
  // end labels, nudged apart only enough to avoid overlap, with a leader to the line end
  const ends = series.map(s => ({ s, y: y(s.values.at(-1)) })).sort((a, b) => a.y - b.y);
  for (let i = 1; i < ends.length; i++) ends[i].ly = Math.max(ends[i].y, (ends[i - 1].ly ?? ends[i - 1].y) + 14);
  ends[0] && (ends[0].ly = ends[0].y);
  series.forEach(s => {
    const pts = s.values.map((v, i) => `${x(i)},${y(v)}`).join(" ");
    svg += dates.length > 1 ? `<polyline fill="none" style="stroke:${s.color}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round" points="${pts}"/>` : "";
    svg += `<circle cx="${x(dates.length - 1)}" cy="${y(s.values.at(-1))}" r="4" style="fill:${s.color};stroke:var(--panel)" stroke-width="2"/>`;
  });
  ends.forEach(e => svg += `<line x1="${x(dates.length - 1) + 6}" x2="${W - m.r + 6}" y1="${e.y}" y2="${e.ly}" style="stroke:var(--grid)"/>
    <text x="${W - m.r + 10}" y="${e.ly + 4}" style="fill:var(--text)">${esc(e.s.short || e.s.label)} ${e.s.values.at(-1)}</text>`);
  svg += `<line class="cross" x1="0" x2="0" y1="${m.t}" y2="${H - m.b}" style="stroke:var(--muted)" stroke-width="1" visibility="hidden"/>
    <rect x="${m.l}" y="0" width="${W - m.l - m.r}" height="${H}" fill="transparent" class="hit"/></svg>`;
  el.innerHTML = svg;
  const svgEl = el.querySelector("svg"), cross = el.querySelector(".cross");
  const move = ev => {
    const r = svgEl.getBoundingClientRect(), px = (ev.clientX - r.left) * W / r.width;
    const i = Math.max(0, Math.min(dates.length - 1, Math.round((px - m.l) / ((W - m.l - m.r) / Math.max(1, dates.length - 1)))));
    cross.setAttribute("x1", x(i)); cross.setAttribute("x2", x(i)); cross.setAttribute("visibility", "visible");
    tooltip(el, `<b>${fmtDate(dates[i])}</b>${series.map(s => tipRow(s.color, s.label, s.values[i])).join("")}`,
            (x(i) / W) * r.width, (ev.clientY - r.top));
  };
  svgEl.querySelector(".hit").addEventListener("pointermove", move);
  svgEl.querySelector(".hit").addEventListener("pointerleave", () => { cross.setAttribute("visibility", "hidden"); tooltip(el, null); });
}

function stackedColumns(el, weeks, series) {  // series: [{label,color,values}] stacked per week
  const W = Math.max(320, el.clientWidth || 600), H = 220, m = { t: 12, r: 8, b: 26, l: 36 };
  const totals = weeks.map((_, i) => series.reduce((a, s) => a + s.values[i], 0));
  const max = niceMax(Math.max(1, ...totals));
  const band = (W - m.l - m.r) / weeks.length, bw = Math.min(24, band * .6);
  const y = v => H - m.b - v / max * (H - m.t - m.b);
  const every = Math.max(1, Math.ceil(weeks.length / Math.max(2, Math.floor((W - m.l - m.r) / 60))));
  let svg = `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="New postings per week by role">`;
  ticks(max).forEach(t => svg += `<line class="gridline" x1="${m.l}" x2="${W - m.r}" y1="${y(t)}" y2="${y(t)}"/><text x="${m.l - 6}" y="${y(t) + 4}" text-anchor="end">${t.toLocaleString()}</text>`);
  weeks.forEach((w, i) => {
    const cx = m.l + band * i + band / 2;
    let base = 0;
    const segs = series.map(s => ({ s, v: s.values[i] })).filter(d => d.v > 0);
    segs.forEach((d, k) => {
      const top = k === segs.length - 1, y0 = y(base), y1 = y(base + d.v), h = Math.max(0, y0 - y1 - (k ? 2 : 0));
      const yTop = y1, r = top ? Math.min(4, h / 2) : 0;
      // rounded data end on the top segment only; 2px surface gap between segments
      svg += r ? `<path style="fill:${d.s.color}" d="M${cx - bw / 2},${yTop + h} V${yTop + r} Q${cx - bw / 2},${yTop} ${cx - bw / 2 + r},${yTop} H${cx + bw / 2 - r} Q${cx + bw / 2},${yTop} ${cx + bw / 2},${yTop + r} V${yTop + h} Z"/>`
               : `<rect style="fill:${d.s.color}" x="${cx - bw / 2}" y="${yTop}" width="${bw}" height="${h}"/>`;
      base += d.v;
    });
    if (i % every === 0 || i === weeks.length - 1) svg += `<text x="${cx}" y="${H - 8}" text-anchor="middle">${fmtShort(w)}</text>`;
    svg += `<rect x="${m.l + band * i}" y="${m.t}" width="${band}" height="${H - m.t - m.b}" fill="transparent" data-i="${i}" class="hit"/>`;
  });
  el.innerHTML = svg + "</svg>";
  const svgEl = el.querySelector("svg");
  svgEl.querySelectorAll(".hit").forEach(h => {
    h.addEventListener("pointermove", ev => {
      const i = +h.dataset.i, r = svgEl.getBoundingClientRect();
      tooltip(el, `<b>Week of ${fmtDate(weeks[i])}</b>${series.map(s => tipRow(s.color, s.label, s.values[i])).join("")}
        <div class="row"><span></span><span>Total</span><span>${totals[i]}</span></div>`, ev.clientX - r.left, ev.clientY - r.top);
    });
    h.addEventListener("pointerleave", () => tooltip(el, null));
  });
}

function horizontalBars(el, rows) {  // rows: [label, value], single series
  const W = Math.max(320, el.clientWidth || 600), rowH = 26, labelW = Math.min(220, W * .42), m = { t: 4, r: 40 };
  const H = m.t + rows.length * rowH, max = Math.max(1, ...rows.map(r => r[1]));
  const x = v => v / max * (W - labelW - m.r);
  let svg = `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Employers with the most new postings">`;
  rows.forEach(([label, v], i) => {
    const y0 = m.t + i * rowH, bh = 14, yb = y0 + (rowH - bh) / 2, w = Math.max(2, x(v)), r = Math.min(4, w / 2);
    const short = label.length > 30 ? label.slice(0, 29) + "…" : label;
    svg += `<text x="${labelW - 8}" y="${y0 + rowH / 2 + 4}" text-anchor="end" style="fill:var(--text)">${esc(short)}<title>${esc(label)}</title></text>
      <path style="fill:var(--pilot)" d="M${labelW},${yb} H${labelW + w - r} Q${labelW + w},${yb} ${labelW + w},${yb + r} V${yb + bh - r} Q${labelW + w},${yb + bh} ${labelW + w - r},${yb + bh} H${labelW} Z"/>
      <text x="${labelW + w + 6}" y="${y0 + rowH / 2 + 4}">${v}</text>`;
  });
  el.innerHTML = svg + "</svg>";
}

function renderTrends() {
  const jobs = state.jobs;
  if (!jobs.length) { $("trend-tiles").innerHTML = `<div class="empty">No data yet.</div>`; return; }
  const start = jobs.map(j => dayOf(j.first_seen)).sort()[0], end = today();
  const dates = dateRange(start, end);
  const colors = Object.fromEntries(ROLES.map(([k]) => [k, `var(--${k})`]));
  // open postings per day: listed on or before the day and not yet closed
  const series = ROLES.map(([k, label]) => ({ key: k, label, short: label.split(" ")[0], color: colors[k], values: dates.map(d =>
    jobs.filter(j => roleOf(j) === k && dayOf(j.first_seen) <= d && (!j.closed_at || dayOf(j.closed_at) > d)).length) }));
  const weekAgo = new Date(Date.now() - 7 * DAY).toISOString(), monthAgo = new Date(Date.now() - 30 * DAY).toISOString();
  const closed = jobs.filter(j => j.closed_at);
  const durations = closed.map(openDays).filter(d => d !== null);
  const strongOpen = jobs.filter(j => j.active && ["strong", "possible"].includes(verdictOf(j))).length;
  $("trend-tiles").innerHTML = [
    ["Open now", jobs.filter(j => j.active).length],
    ["New in the last 7 days", jobs.filter(j => j.first_seen >= weekAgo && dayOf(j.first_seen) > start).length, "excludes the first poll"],
    ["Closed in the last 7 days", closed.filter(j => j.closed_at >= weekAgo).length],
    ["Median days open", median(durations) ?? "–", durations.length ? `${durations.length} closed postings` : "none closed yet"],
    ["Open strong / possible matches", strongOpen],
  ].map(([label, value, hint]) => `<div class="tile"><div class="label">${label}</div><div class="value">${typeof value === "number" ? value.toLocaleString() : value}</div>${hint ? `<div class="hint">${hint}</div>` : ""}</div>`).join("");

  $("open-note").textContent = `Since tracking began on ${fmtDate(start)}`;
  $("open-legend").innerHTML = legendHtml(series.map(s => [s.color, s.label]));
  lineChart($("open-chart"), dates, series);
  $("open-table").innerHTML = tableHtml(["Date", ...series.map(s => s.label)], dates.map((d, i) => [fmtDate(d), ...series.map(s => s.values[i])]).reverse());

  const weeks = dateRange(weekStart(start), end).filter(d => weekStart(d) === d);
  const weekly = ROLES.map(([k, label]) => ({ label, color: colors[k], values: weeks.map(w =>
    jobs.filter(j => roleOf(j) === k && weekStart(dayOf(j.first_seen)) === w).length) }));
  $("weekly-legend").innerHTML = legendHtml(weekly.map(s => [s.color, s.label])) +
    `<span>First week includes every posting already open when tracking began</span>`;
  stackedColumns($("weekly-chart"), weeks, weekly);
  $("weekly-table").innerHTML = tableHtml(["Week of", ...weekly.map(s => s.label), "Total"],
    weeks.map((w, i) => [fmtDate(w), ...weekly.map(s => s.values[i]), weekly.reduce((a, s) => a + s.values[i], 0)]).reverse());

  const byCompany = {};
  jobs.filter(j => j.first_seen >= monthAgo).forEach(j => byCompany[j.company] = (byCompany[j.company] || 0) + 1);
  const top = Object.entries(byCompany).sort((a, b) => b[1] - a[1]).slice(0, 10);
  horizontalBars($("employers-chart"), top);
  $("employers-table").innerHTML = tableHtml(["Employer", "New postings"], Object.entries(byCompany).sort((a, b) => b[1] - a[1]));

  $("duration-table").innerHTML = closed.length ? tableHtml(["Role", "Closed postings", "Median days open", "Shortest", "Longest"],
    ROLES.map(([k, label]) => { const d = closed.filter(j => roleOf(j) === k).map(openDays).filter(v => v !== null);
      return [label, d.length, median(d) ?? "–", d.length ? Math.min(...d) : "–", d.length ? Math.max(...d) : "–"]; }))
    : `<p class="note">No postings have closed yet. This fills in as boards remove listings.</p>`;
}
document.querySelectorAll(".table-toggle").forEach(b => b.addEventListener("click", () => {
  const t = $(`${b.dataset.table}-table`); t.hidden = !t.hidden; b.textContent = t.hidden ? "Show table" : "Hide table";
}));
let resizeTimer;
window.addEventListener("resize", () => { clearTimeout(resizeTimer); resizeTimer = setTimeout(() => { if (!$("tab-trends").hidden) renderTrends(); }, 150); });

/* ---------- wiring ---------- */
function renderAll() {
  $("app-count").textContent = tracker.list().length ? `(${tracker.list().length})` : "";
  renderJobs();
  if (!$("tab-apps").hidden) renderApps();
}
document.addEventListener("change", e => {
  const id = e.target.dataset.track;
  if (id !== undefined) {
    const job = state.byId[id] || tracker.get(id);
    tracker.setStatus(id, e.target.value, job);
    renderAll();
    return;
  }
  const card = e.target.closest("[data-app]"), field = e.target.dataset.field;
  if (card && field) { const a = tracker.get(card.dataset.app); a[field] = e.target.value; tracker.save(a); }
});
document.addEventListener("click", e => {
  const apply = e.target.closest("[data-apply]");
  if (apply) openApply(apply.dataset.apply);
  const rm = e.target.closest("[data-remove]");
  if (rm && confirm("Remove this application from the tracker?")) { tracker.setStatus(rm.dataset.remove, ""); renderAll(); }
});
$("stats").addEventListener("click", e => {
  const el = e.target.closest(".stat");
  if (el) { state.verdict = el.dataset.v; renderJobs(); }
});
["q", "company", "sort", "closed", "role", "hide-tracked"].forEach(id => $(id).addEventListener("input", renderJobs));
$("app-filter").innerHTML += STATUSES.map(([v, l]) => `<option value="${v}">${l}</option>`).join("");
$("app-filter").addEventListener("input", renderApps);

$("add-form").status.innerHTML = STATUSES.map(([v, l]) => `<option value="${v}" ${v === "applied" ? "selected" : ""}>${l}</option>`).join("");
$("add-app").onclick = () => { $("add-form").hidden = false; $("add-form").applied_on.value = today(); $("add-form").company.focus(); };
$("cancel-add").onclick = () => { $("add-form").hidden = true; };
$("add-form").addEventListener("submit", e => {
  e.preventDefault();
  const f = Object.fromEntries(new FormData(e.target));
  tracker.save(sanitizeApp({ id: `manual:${Date.now().toString(36)}`, company: f.company, title: f.title, location: f.location,
    url: f.url, apply_url: f.url, role: f.role, status: f.status, applied_on: f.applied_on || null, notes: "",
    history: [{ status: f.status, at: new Date().toISOString() }] }));
  e.target.reset(); e.target.hidden = true; renderAll(); renderApps();
});
$("export-apps").onclick = () => {
  const blob = new Blob([JSON.stringify(tracker.file(), null, 1)], { type: "application/json" });
  const a = Object.assign(document.createElement("a"), { href: URL.createObjectURL(blob), download: `applications-${today()}.json` });
  a.click(); URL.revokeObjectURL(a.href);
};
$("import-apps").addEventListener("change", async e => {
  const file = e.target.files[0]; if (!file) return;
  try { tracker.merge(JSON.parse(await file.text()).applications); sync.schedule(); renderAll(); renderApps(); }
  catch (err) { alert(`Could not import: ${err.message}`); }
  e.target.value = "";
});
$("sync-settings").onclick = () => {
  const f = $("sync-form"), c = sync.cfg || {};
  f.repo.value = c.repo || ""; f.path.value = c.path || "data/applications.json"; f.branch.value = c.branch || ""; f.token.value = c.token || "";
  f.hidden = false;
};
$("cancel-sync").onclick = () => { $("sync-form").hidden = true; };
$("disconnect-sync").onclick = () => { sync.cfg = null; vault.data.sync = null; vault.save(); $("sync-form").hidden = true; sync.status("Saved in this browser only"); };
$("sync-form").addEventListener("submit", e => {
  e.preventDefault();
  const f = Object.fromEntries(new FormData(e.target));
  const cfg = { repo: f.repo.trim(), path: f.path.trim(), branch: f.branch.trim(), token: f.token.trim() };
  if (!sync.valid(cfg)) { alert("Check the repository (owner/name), a .json file path, and a GitHub token (github_pat_…)."); return; }
  sync.cfg = vault.data.sync = cfg; vault.save(); e.target.hidden = true; sync.sha = null; sync.pull();
});

/* =====================================================================
   Boot: unlock, decrypt, render
   ===================================================================== */
function start(data) {
  data.jobs = (data.jobs || []).map(sanitizeJob);
  state.jobs = data.jobs; state.updated = data.updated;
  state.byId = Object.fromEntries(data.jobs.map(j => [j.id, j]));
  $("login").hidden = true; $("app").hidden = false;
  $("lock").hidden = vault.plaintext;
  $("updated").textContent = `Last polled ${data.updated ? new Date(data.updated).toLocaleString() : "never"} · ${data.jobs.filter(j => j.active).length} open postings`
    + (vault.plaintext ? " · UNENCRYPTED DEVELOPMENT BUILD" : "");
  [...new Set(data.jobs.map(j => j.company))].sort()
    .forEach(c => $("company").insertAdjacentHTML("beforeend", `<option>${esc(c)}</option>`));
  return vault.load().then(() => {
    tracker.apps = {};
    tracker.merge(Object.values(vault.data.applications || {}));
    sync.cfg = vault.data.sync && sync.valid(vault.data.sync) ? vault.data.sync : null;
    renderAll();
    showTab(store.get("tab", "jobs"));
    sync.pull();
  });
}

function showLogin(blob) {
  $("login").hidden = false; $("app").hidden = true;
  $("password").focus();
  $("login-form").onsubmit = async e => {
    e.preventDefault();
    const button = $("login-form").querySelector("button");
    button.disabled = true; button.textContent = "Unlocking…"; $("login-error").hidden = true;
    try {
      const key = await vault.derive($("password").value, blob.salt, blob.iter || 600000);
      const data = await vault.decrypt(blob, key);  // AES-GCM: throws on a wrong password
      vault.key = key;
      $("password").value = "";
      if ($("remember").checked) await keystore.put({ key, salt: blob.salt });
      await start(data);
    } catch {
      await new Promise(r => setTimeout(r, 600));
      $("login-error").hidden = false;
    } finally { button.disabled = false; button.textContent = "Unlock"; }
  };
}

$("lock").onclick = async () => {
  await keystore.clear();
  vault.key = null; tracker.apps = {}; sync.cfg = null;
  location.reload();
};

(async () => {
  try {
    const res = await fetch("jobs.enc.json", { cache: "no-store" });
    if (res.ok) {
      const blob = await res.json();
      vault.salt = blob.salt; vault.iter = blob.iter || 600000;
      const remembered = await keystore.get();
      if (remembered && remembered.salt === blob.salt) {
        try { vault.key = remembered.key; return await start(await vault.decrypt(blob)); }
        catch { vault.key = null; await keystore.clear(); }  // password changed since this device was remembered
      }
      return showLogin(blob);
    }
    const dev = await fetch("jobs.json", { cache: "no-store" });  // local development build only
    if (!dev.ok) throw new Error(`no job data (HTTP ${res.status})`);
    vault.plaintext = true;
    await start(await dev.json());
  } catch (e) {
    $("login").hidden = false; $("login-form").hidden = true;
    $("login-error").hidden = false; $("login-error").textContent = `Could not load job data: ${e.message}`;
  }
})();
